### PR TITLE
Fix await next to actually wait for new input

### PR DESCRIPTION
**Pull request by JanEricNitschke**
Loop never actually waited for new input in next statements.

And even if it did it actually stored the old value in the nexted variable.
I have adjusted the latter only for `await next` as i did not have a look at "normal next" at all. So if it should also be adjusted there just tell me and i will add that.

### CODE REVIEW

**Comment by vivaansinghvi07** [comment]
Are you sure removing the match statement would correct? IIRC if you do something like `await next func`, `func` will be a Name (as it was defined as a function definer) so then the `old_len` really is None, needing the check. Also, I'm pretty sure it was there in case someone does something like `await next val + val`, and I had wanted to store that previous value of val, hence the `prev_values[i]` access

**Comment by JanEricNitschke** [comment]
I actually did test `print(await next score + score)` and it was correct. I think the old value got handled somewhere else.

I did not check with func.

**Comment by vivaansinghvi07** [comment]
Ah okay, sounds good! I'll go ahead and merge it now (since I am about to sleep), but could you check the other example at some point?

**Comment by JanEricNitschke** [comment]
I probably wont manage today and i will be on vacation for three weeks after.

I think it might also make sense to create a CI that just runs some programs and parses the printed output against an expectation.

Then you could easily add any new issue that comes up as a new test case and be confident that new changes to fix these dont cause regressions on previous ones.

**Comment by vivaansinghvi07** [comment]
Agreed, adding tests would definitely be a good idea

**Pull request merged**
